trello/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('trello_app.urls'))
]

trello_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'trello'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user_detail/<int:pk>/', views.UserDetailView.as_view(), name='user_detail'),
    path('user_detail/<int:pk>/user_update/', views.UserUpdateView.as_view(), name='user_update'),
    path('lists/create/', views.ListCreateView.as_view(), name='lists_create'),
    path('lists/', views.ListListView.as_view(), name='lists_list'),
    path('lists/<int:pk>/', views.ListDetailView.as_view(), name='lists_detail'),
    path('lists/<int:pk>/update/', views.ListUpdateView.as_view(), name='lists_update'),
    path('lists/<int:pk>/delete/', views.ListDeleteView.as_view(), name='lists_delete'),
    path('cards/create/', views.CardCreateView.as_view(), name='cards_create'),
    path('cards/', views.CardListView.as_view(), name='cards_list'),
    path('cards/<int:pk>/', views.CardDetailView.as_view(), name='cards_detail'),
    path('cards/<int:pk>/update/', views.CardUpdateView.as_view(), name='cards_update'),
    path('cards/<int:pk>/delete/', views.CardDeleteView.as_view(), name='cards_delete'),
    path('cards/create/<int:list_pk>/', views.CardCreateFromHomeView.as_view(), name='cards_create_from_index')
]

trello_app/models.py
from django.db import models
from django.contrib.auth.models import User

class List(models.Model):
    title = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Card(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    list = models.ForeignKey(List, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

trello_app/forms.py
from django import forms
from .models import User, List, Card
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['palceholder'] = field.label


class UserForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = User
        fields = ('username', 'last_name', 'first_name', 'email',)


class ListForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ListForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = List
        fields = ('title',)

class CardForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(CardForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Card
        fields = ('title', 'description', 'list')

class CardCreateFromHomeForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(CardCreateFromHomeForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Card
        fields = ('title', 'description',)

class CardUpdateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(CardUpdateForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Card
        fields = ("title", "description", "list")

trello_app/views.py
from django.shortcuts import render, redirect, resolve_url, get_object_or_404
from .models import User, List, Card
from django.views.generic import CreateView, TemplateView, DetailView, UpdateView, ListView, DeleteView
from django.contrib.auth import login, authenticate
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy

from .forms import UserForm, SignUpForm, LoginForm, ListForm, CardForm, CardCreateFromHomeForm
from .mixins import OnlyYouMixin




class IndexView(ListView):
    model = List
    template_name = 'index.html'



class SignUp(CreateView):
    form_class = SignUpForm
    template_name = 'signup.html'

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('trello:index')
        return render(request, 'signup.html', {'form': form})

class Login(LoginView):
    form_class = LoginForm
    template_name = 'login.html'

class Logout(LogoutView):
    template_name = 'logout.html'


class UserDetailView(OnlyYouMixin, DetailView):
    model = User
    template_name = 'user_detail.html'

class UserUpdateView(OnlyYouMixin, UpdateView):
    model = User
    template_name = 'user_update.html'
    form_class = UserForm

    def get_success_url(self):
        return resolve_url('trello:user_detail', pk=self.kwargs['pk'])


class ListCreateView(CreateView):
    model = List
    template_name = 'create.html'
    form_class = ListForm
    success_url = reverse_lazy('trello:index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class ListListView(ListView):
    model = List
    template_name = 'list.html'

class ListDetailView(DetailView):
    model = List
    template_name = 'list_detail.html'

class ListUpdateView(UpdateView):
    model = List
    template_name = 'list_update.html'
    form_class = ListForm
    success_url = reverse_lazy('trello:index')


class ListDeleteView(DeleteView):
    model = List
    template_name = 'delete.html'
    form_class = ListForm
    success_url = reverse_lazy('trello:index')

class CardCreateView(CreateView):
    model = Card
    template_name = 'cards/create.html'
    form_class = CardForm
    success_url = reverse_lazy('trello:index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class CardListView(ListView):
    model = Card
    template_name = 'cards/list.html'

class CardDetailView(DetailView):
    model = Card
    template_name = 'cards/detail.html'


class CardUpdateView(UpdateView):
    model = Card
    template_name = 'cards/update.html'
    form_class = CardForm
    success_url = reverse_lazy('trello:index')

class CardDeleteView(DeleteView):
    model = Card
    template_name = 'cards/delete.html'
    form_class = CardForm
    success_url = reverse_lazy('trello:index')

class CardCreateFromHomeView(CreateView):
    model = Card
    template_name = 'create.html'
    form_class = CardCreateFromHomeForm
    success_url = reverse_lazy('trello:index')

    def form_valid(self, form):
        list_pk = self.kwargs['list_pk']
        list_instance = get_object_or_404(List, pk=list_pk)
        form.instance.list = list_instance
        form.instance.user = self.request.user
        return super().form_valid(form)

trello_app/templates/base.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/base.css' %}">
{% block customcss %}

{% endblock customcss %}

<title>trello</title>

</head>
{% include 'navbar.html' %}
<body>

{% block content %}

{% endblock content %}

</body>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</html>

trello_app/templates/cards/create.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
<h1>カード作成</h1>
    <form action="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">送信</button>
    </form>
</div>
{% endblock %}

trello_app/templates/cards/delete.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1>カード削除</h1>
  <form method="post">
    {% csrf_token %}
    <p>カード "{{ card.title }}" を本当に削除してもよろしいですか？</p>
    <button type="submit" class="btn btn-danger">確認</button>
  </form>
</div>
{% endblock %}

trello_app/templates/cards/detail.html
{% extends "base.html" %}

{% block content %}

<h1>カード詳細</h1>
<dl class="row">
  <dt class="col-sm-3">タイトル</dt>
  <dd class="col-sm-9">{{ card.title }}</dd>
  <dt class="col-sm-3">詳細</dt>
  <dd class="col-sm-9">{{ card.description }}</dd>
  <dt class="col-sm-3">リスト名</dt>
  <dd class="col-sm-9">{{ card.list.title }}</dd>
  <dt class="col-sm-3">ユーザー名</dt>
  <dd class="col-sm-9">{{ card.user.username }}</dd>
</dl>

<a class="btn btn-primary" href="{% url 'trello:cards_update' card.pk  %}" role="button">編集</a>
<a class="btn btn-danger" href="{% url 'trello:cards_delete' card.pk  %}" role="button">削除</a>


{% endblock %}

trello_app/templates/cards/list.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1>カード一覧</h1>
  <a class="btn btn-primary my-3" href="{% url 'trello:cards_create' %}" role="button">作成</a>
  <div class="card-columns">
    {% for card in card_list %}
    <a href="{% url 'trello:cards_detail' card.pk %}" class="card">
      <div class="card-body">
        <h5 class="card-title">{{ card.title }}</h5>
        <footer>
          <small class="text-muted">作成者: {{ card.user.username }}</small>
        </footer>
      </div>
    </a>
    {% endfor %}
  </div>
</div>
{% endblock %}

trello_app/templates/cards/update.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1>カード編集</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">送信</button>
  </form>
</div>
{% endblock %}

trello_app/templates/create.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<h2>リスト作成</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">送信</button>
    </form>
</div>
{% endblock content %}

trello_app/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<h1>リスト削除</h1>
    <form action="post">
    {% csrf_token %}
    <p>リスト"{{ list.title }}"を本当に削除してもよろしいですか？</p>
    <button type="submit" class="btn btn-danger">削除</button>
    </form>
{% endblock %}

trello_app/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block customcss %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}

<div class="container-fluid home" style="display: table-cell !important" >
  <div class="row flex-nowrap">
    {% for list in list_list %}
    <div class="bg-light m-3 p-2 list">
      <h4>{{ list.title }}
        <a href="{% url 'trello:lists_update' list.pk %}" class="text-dark"><i class="far fa-edit fa-xs"></i></a>
        <a href="{% url 'trello:lists_delete' list.pk %}" class="text-dark"><i class="far fa-trash-alt fa-xs"></i></a>
      </h4>

      {% for card in list.card_set.all %}
      <a href="{% url 'trello:cards_detail' card.pk %}" class="card m-3">
        <div class="card-body">
          <h5 class="card-title">{{ card.title }}</h5>
          <footer>
            <small class="text-muted">作成者: {{ card.user.username }}</small>
          </footer>
        </div>
      </a>
      {% endfor %}
      <a href="{% url 'trello:cards_create_from_index' list.pk %}" class="text-dark"><i class="far fa-plus-square"></i> さらにカードを追加</a>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}

trello_app/templates/list.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<h1>リスト一覧</h1>
<a href="{% url 'trello:lists_create' %}" class="btn btn-primary my-3" role="button">作成</a>
<div class="card-columns">
    {% for list in list_list %}
    <a href="{% url 'trello:lists_detail' list.pk %}" class="card">
    <div class="card">
    <div class="card-body">
        <h5 class="card-title">{{ list.title }}</h5>
        <footer>
            <small class="text-muted">作成者: {{ list.user.username }}</small>
        </footer>
    </div>
    </div>
    </a>
    {% endfor %}
</div>
</div>
{% endblock content %}

trello_app/templates/list_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<h1>リスト詳細</h1>
<dl class="row">
    <dt class="col-sm-3">タイトル</dt>
    <dd class="col-sm-9">{{ list.title }}</dd>
    <dt class="col-sm-3">ユーザー名</dt>
    <dd class="col-sm-9">{{ list.user.username }}</dd>
</dl>
<a class="btn btn-primary" href="{% url 'trello:lists_update' list.pk  %}" role="button">編集</a>
<a class="btn btn-danger" href="{% url 'trello:lists_delete' list.pk  %}" role="button">削除</a>
</div>
{% endblock content %}

trello_app/templates/list_update.html
{% extends 'base.html' %}
{% block content %}
<h1>リスト編集</h1>
    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">送信</button>
    </form>
{% endblock content %}

trello_app/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block customcss %}
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
{% endblock customcss %}
{% block content %}
<main>
<div class="container">
<h1>ログイン</h1>
    <form action="" method="post">
    <br>
    {{ form.non_field_errors }}
    {% for field in form %}
    <p>{{ field.label}}</p>
    {{ field }}
    {{ field.errors }}
    <br>
    {% endfor %}
    <button type="submit" class="btn btn-primary" >ログイン</button>
    <input type="hidden" name="next" value="{{ next }}" />
    {% csrf_token %}
    </form>
    <br>
    <hr>
    <p>まだアカウントがない方は<a href="{% url 'trello:signup' %}">こちら</a></p>
</div>
</main>
{% endblock content %}

trello_app/templates/logout.html
{% extends 'base.html' %}
{% load static %}
{% block customcss %}
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
{% endblock customcss %}
{% block content %}
    <div class="container">
    <h4>またのご利用をお待ちしております。</h4>
        <a href="{% url 'trello:login' %}" class="btn btn-primary">ログインページへ</a>
    </div>
{% endblock %}

trello_app/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #0000cd">
<a class="navbar-brand" href="{% url 'trello:index' %}"><img src='{% static 'image/logo.png' %}' alt=""></a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
<ul class="navbar-nav mr-auto">
</ul>

<ul class="navbar-nav">
    {% if user.is_authenticated %}
    <li class="nav-item">
        <a href="{% url 'trello:lists_list' %}" class="nav-link" style="color: white">リスト一覧</a>
    </li>
    <li class="nav-item">
        <a href="{% url 'trello:cards_list' %}" class="nav-link" style="color: white">カード一覧</a>
    </li>
    <li class="nav-item">
        <a href="{% url 'trello:logout' %}" class="nav-link" style="color: white">ログアウト</a>
    </li>
    <li class="nav-item">
        <a href="{% url 'trello:user_detail' pk=user.pk %}" class="btn btn-primary">マイページ </a>
    </li>
    {% else %}
    <li class="nav-item">
        <a href="{% url 'trello:login' %}" class="nav-link" style="color: white">ログイン</a>
    </li>
    <li>
        <a href="{% url 'trello:signup' %}" class="nav-link" style="color: white">新規会員登録</a>
    </li>
    {% endif %}
</ul>
</div>
</nav>

trello_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block customcss %}
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
{% endblock customcss %}
{% block content %}
<div class="content">
<main>
<div class="container">
<h1>サインアップ</h1>
    <form action="" method="post">
    <br>
    {{ form.non_field_errors }}
    {% for field in form %}
    <p>{{ field.label}}</p>
    {{ field }}
    {{ field.errors }}
    <br>
    {% endfor %}
    <br>
    <button type="submit" class="btn btn btn-primary" >登録してログイン</button>
    <input type="hidden" name="next" value="{{ next }}" />
    {% csrf_token %}
    </form>
    <br>
    <br>
    <br>
    <br>
</div>
</main>
</div>
{% endblock content %}

trello_app/templates/user_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<h1>ユーザー詳細</h1>
    <dl class="row">
    <dt class="col-sm-3">ユーザー名</dt>
    <dd class="col-sm-9">{{ user.username }}</dd>
    <dt class="col-sm-3">姓</dt>
    <dd class="col-sm-9">{{ user.last_name }}</dd>
    <dt class="col-sm-3">名</dt>
    <dd class="col-sm-9">{{ user.first_name }}</dd>
    <dt class="col-sm-3">メールアドレス</dt>
    <dd class="col-sm-9">{{ user.email }}</dd>
    </dl>
    <br>
    {% if user.pk == request.user.pk %}
    <a href="{% url 'trello:user_update' pk=user.pk %}" class="btn btn-primary">編集ページ</a>
    {% else %}
    <a href="#" class="btn btn-primary disabled" role="button">編集</a>
    {% endif %}
</div>
{% endblock content %}

trello_app/templates/user_update.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <h1>ユーザー編集</h1>
  <form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">送信</button>
  </form>
</div>
{% endblock content %}